// @flow

import { keyMirror } from '../utils';

export default keyMirror([
    'ACCOUNT_DEFAULT_SET',
    'ACCOUNT_RESET_LOGIN_STATE',
    'ACCOUNT_MAKE_SIGN_IN_ACTIVE',
    'ACCOUNT_MAKE_SIGN_UP_ACTIVE',
    'ACCOUNT_MAKE_FORGOT_PASSWORD_ACTIVE',
    'ACCOUNT_SIGN_IN',
    'ACCOUNT_SIGN_IN_ERROR',
    'ACCOUNT_SIGN_IN_NETWORK_ERROR',
    'ACCOUNT_SIGN_IN_SUCCESS',
    'ACCOUNT_SIGN_UP',
    'ACCOUNT_SIGN_UP_ERROR',
    'ACCOUNT_SIGN_UP_NETWORK_ERROR',
    'ACCOUNT_SIGN_UP_SUCCESS',
    'ACCOUNT_RESTORE_PASSWORD',
    'ACCOUNT_RESTORE_PASSWORD_NETWORK_ERROR',
    'ACCOUNT_RESTORE_PASSWORD_ERROR',
    'ACCOUNT_RESTORE_PASSWORD_SUCCESS',
]);
